/**
 * Represents a single ingredient in a recipe.
 */
export interface Ingredient {
  /** The name of the ingredient (e.g., "Sugar"). */
  item: string;
  /** The quantity of the ingredient. */
  quantity: number;
  /** The unit of measurement (e.g., "cups", "grams"). */
  unit: string;
}

/**
 * Represents a culinary recipe.
 */
export interface Recipe {
  /** Unique identifier for the recipe. */
  id: string;
  /** The name of the dish. */
  name: string;
  /** A brief description of the recipe. */
  description: string;
  /** List of ingredients required. */
  ingredients: Ingredient[];
  /** Step-by-step cooking instructions. */
  instructions: string[];
  /** Preparation time (e.g., "15 mins"). */
  prepTime: string;
  /** Cooking time (e.g., "45 mins"). */
  cookTime: string;
  /** Number of servings the recipe yields. */
  servings: number;
  /** List of dietary tags (e.g., "Vegan", "Gluten-Free"). */
  dietary: string[];
}

/**
 * Represents a budget range for a gift.
 */
export interface GiftBudget {
  /** Minimum price. */
  min: number;
  /** Maximum price. */
  max: number;
}

/**
 * Represents a gift suggestion.
 */
export interface Gift {
  /** Unique identifier for the gift. */
  id: string;
  /** The name of the gift item. */
  name: string;
  /** Description of the gift and why it's suitable. */
  description: string;
  /** Targeted recipient types (e.g., "Dad", "Teenager"). */
  recipient: string[];
  /** Related interests (e.g., "Technology", "Gardening"). */
  interests: string[];
  /** The price range for the gift. */
  budget: GiftBudget;
  /** Optional URL to purchase or view the gift. */
  link?: string;
}

/**
 * Payload structure for voice commands processing.
 */
export interface VoiceCommandPayload {
  /** The transcribed text command from the user. */
  command?: string;
}

/**
 * Agent-authored note that can be text or a small table.
 */
export interface AgentNote {
  /** Unique ID for the note. */
  id: string;
  /** The title or header of the note. */
  title: string;
  /** The display type of the note. */
  type: 'text' | 'table';
  /** Content for text-type notes. */
  content?: string;
  /** Rows for table-type notes. */
  tableRows?: string[][];
}

/**
 * User preferences for personalization.
 */
export interface Preferences {
  dietary: {
    allergies: string[];
    dislikes: string[];
    diets: string[]; // e.g. "Vegan", "Keto"
  };
  gifts: {
    recipientRelationship: string; // e.g. "Mother", "Colleague"
    recipientAge: number | null;
    recipientInterests: string[];
    budgetMin: number;
    budgetMax: number;
    dislikes: string[];
  };
  decorations: {
    room: string;
    style: string; // e.g. "Modern", "Rustic"
    preferredColors: string[];
  };
}

/**
 * A single step within an agent's high-level plan.
 */
export interface PlanStep {
  /** Unique ID for the step (e.g., "step-1"). */
  id: string;
  /** Description of the action or goal for this step. */
  description: string;
  /** Current execution status of the step. */
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
}

/**
 * Represents a high-level plan generated by the agent.
 */
export interface AgentPlan {
  /** Unique ID for the plan. */
  id: string;
  /** A descriptive title for the overall plan. */
  title: string;
  /** An ordered list of steps to execute the plan. */
  steps: PlanStep[];
}
