import express from 'express';
import request from 'supertest';
import giftRoutes from '../routes/gifts';
import { Gift } from '../models/types';
import { tools } from '../tools';

// Mock tools
jest.mock('../tools', () => ({
  tools: {
    find_gift: {
      function: jest.fn(),
    },
  },
}));

// Mock Redis
jest.mock('../config/db', () => {
  const mockStore: Record<string, any> = {};
  return {
    __esModule: true,
    default: {
      hSet: jest.fn(async (key: string, value: Record<string, string>) => {
        if (!mockStore[key]) mockStore[key] = {};
        Object.assign(mockStore[key], value);
        return 1;
      }),
      hGetAll: jest.fn(async (key: string) => {
        return mockStore[key] || {};
      }),
      sAdd: jest.fn(async (key: string, member: string) => {
        if (!mockStore[key]) mockStore[key] = new Set();
        (mockStore[key] as Set<string>).add(member);
        return 1;
      }),
      sMembers: jest.fn(async (key: string) => {
        const val = mockStore[key];
        return val instanceof Set ? Array.from(val) : [];
      }),
      flushAll: jest.fn(async () => {
        for (const key in mockStore) delete mockStore[key];
      }),
      on: jest.fn(),
      connect: jest.fn(),
    },
  };
});

import redisClient from '../config/db';

const app = express();
app.use(express.json());
app.use('/api/gifts', giftRoutes);

beforeAll(async () => {
  const gifts: Gift[] = [
    {
      id: '1',
      name: 'Cozy Winter Scarf',
      description: 'A warm and stylish scarf, perfect for cold weather.',
      recipient: ['mom', 'friend', 'sister'],
      interests: ['fashion', 'comfort'],
      budget: { min: 20, max: 30 },
      link: 'https://example.com/scarf',
    },
    {
      id: '2',
      name: 'Gardening Tool Set',
      description: 'A durable and ergonomic set of tools for the avid gardener.',
      recipient: ['grandma', 'aunt', 'gardener'],
      interests: ['gardening', 'outdoors'],
      budget: { min: 50, max: 80 },
      link: 'https://example.com/gardening-set',
    },
  ];

  await redisClient.flushAll();

  for (const gift of gifts) {
    await redisClient.hSet(`gift:${gift.id}`, { data: JSON.stringify(gift) });
    await redisClient.sAdd('gifts', `gift:${gift.id}`);
  }
});

afterAll(async () => {
  await redisClient.flushAll();
});

describe('Gift API', () => {
  beforeEach(() => {
    (tools.find_gift.function as jest.Mock).mockClear();
  });

  // Redis-based tests
  test('returns all gifts if no filters are applied', async () => {
    const res = await request(app).get('/api/gifts');
    expect(res.statusCode).toEqual(200);
    expect(res.body.length).toBeGreaterThan(0);
    expect(tools.find_gift.function).not.toHaveBeenCalled();
  });

  test('filters gifts by budget range (Redis)', async () => {
    const res = await request(app).get('/api/gifts?budgetMin=20&budgetMax=40');
    expect(res.statusCode).toEqual(200);
    expect(res.body.every((gift: Gift) => gift.budget.min >= 20 && gift.budget.max <= 40)).toBeTruthy();
  });

  test('returns a specific gift by ID (Redis)', async () => {
    const res = await request(app).get('/api/gifts/1');
    expect(res.statusCode).toEqual(200);
    expect(res.body).toHaveProperty('id', '1');
  });

  test('returns 404 for a nonexistent gift ID', async () => {
    const res = await request(app).get('/api/gifts/999');
    expect(res.statusCode).toEqual(404);
    expect(res.body).toHaveProperty('message', 'Gift not found');
  });

  // LLM-based tests
  test('uses LLM tool when recipient is provided', async () => {
    const mockGifts = [{
        name: 'LLM Gift',
        description: 'Generated by LLM',
        budget: { min: 10, max: 20 },
    }];
    (tools.find_gift.function as jest.Mock).mockResolvedValue(mockGifts);

    const res = await request(app).get('/api/gifts?recipient=mom');
    expect(res.statusCode).toEqual(200);
    expect(res.body).toHaveLength(1);
    expect(res.body[0].name).toEqual('LLM Gift');
    expect(res.body[0].id).toMatch(/^gen-/);
    expect(tools.find_gift.function).toHaveBeenCalledWith(expect.stringContaining('recipient: mom'));
  });

  test('uses LLM tool when interests are provided', async () => {
    const mockGifts = [{
        name: 'Tech Gift',
        description: 'For tech lovers',
        budget: { min: 50, max: 100 },
    }];
    (tools.find_gift.function as jest.Mock).mockResolvedValue(mockGifts);

    const res = await request(app).get('/api/gifts?interests=tech');
    expect(res.statusCode).toEqual(200);
    expect(res.body[0].name).toEqual('Tech Gift');
    expect(tools.find_gift.function).toHaveBeenCalledWith(expect.stringContaining('interests: tech'));
  });

  test('filters LLM results by budget if provided', async () => {
    const mockGifts = [
        { name: 'Cheap Gift', budget: { min: 10, max: 20 } },
        { name: 'Expensive Gift', budget: { min: 100, max: 200 } }
    ];
    (tools.find_gift.function as jest.Mock).mockResolvedValue(mockGifts);

    const res = await request(app).get('/api/gifts?interests=misc&budgetMax=50');
    expect(res.statusCode).toEqual(200);
    expect(res.body).toHaveLength(1);
    expect(res.body[0].name).toEqual('Cheap Gift');
  });
});